### ISSUE TITLE
Publish app on f-droid

### ISSUE THREAD

**Issue by joe733** [jld3103/nextcloud-harbour#18]
[F-Droid | App Developers | FAQ](https://f-droid.org/docs/FAQ_-_App_Developers/)

**Comment by jld3103** [comment]
Template for submission later:
```
Categories:
  - Internet
License: BSD-3-Clause
AuthorName: jld3103
SourceCode: https://github.com/jld3103/nextcloud-harbour
Liberapay: jld3103

AutoName: Nextcloud Harbour

RepoType: git
Repo: https://github.com/jld3103/nextcloud-harbour

Builds:
  - versionName: 1.0.0
    versionCode: 1
    commit: dce04ed
    subdir: packages/harbour
    output: build/app/outputs/flutter-apk/app-release-unsigned.apk
    srclibs:
      - flutter@3.0.5
    build:
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter packages pub get
      - $$flutter$$/bin/flutter build apk --no-tree-shake-icons

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: packages/harbour/pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 1.0.0
CurrentVersionCode: 1
```

I think once I make a first proper `1.0.0` release I'll make a MR for inclusion in the official F-Droid repo.
